"""Hand-written demo mail for the README screenshot, added to a dev corpus.

Five messages about a bathroom remodel: a quote with an itemised PDF estimate,
a competing quote in the body, a note comparing them, and a scheduling thread.
Everything is invented and on reserved .example domains. This repository is
public: never put real mail here.

Usage: python3 assets/screenshots/demo-mail.py ~/MailvecDemo/Mail
Procedure: assets/screenshots/README.md
"""
import sys, os, email.utils
from email.message import EmailMessage
from datetime import datetime, timezone, timedelta

root = os.path.abspath(os.path.expanduser(sys.argv[1]))
# Only ever write into a Maildir tools/Mailvec.DevCorpus generated: the corpus
# directory beside it holds the manifest and the generated env.sh.
corpus = os.path.dirname(root)
try:
    with open(os.path.join(corpus, "env.sh")) as f:
        generated = "Generated by tools/Mailvec.DevCorpus" in f.read()
except OSError:
    generated = False
if not (generated and os.path.isfile(os.path.join(corpus, "manifest.json"))):
    sys.exit(f"refusing: {root} is not the Mail/ directory of a generated dev corpus")
EDT = timezone(timedelta(hours=-4))
SAM = "Sam Rivera <sam@example.org>"
ADA = "Ada Example <ada@example.com>"


def text_pdf(lines):
    """A minimal one-page text PDF (Helvetica), parseable by PdfPig."""
    def esc(s):
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    ops = ["BT", "/F1 11 Tf", "14 TL", "56 760 Td"]
    for i, (size, line) in enumerate(lines):
        ops.append(f"/F1 {size} Tf")
        ops.append(f"({esc(line)}) Tj T*")
    ops.append("ET")
    stream = "\n".join(ops).encode("latin-1")
    objs = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for n, body in enumerate(objs, 1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % n + body + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 %d\n0000000000 65535 f \n" % (len(objs) + 1)
    for o in offsets:
        out += b"%010d 00000 n \n" % o
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (len(objs) + 1, xref)
    return bytes(out)


def msg(mid, frm, to, subject, when, body, reply_to=None, refs=(), attach=None):
    m = EmailMessage()
    m["Date"] = email.utils.format_datetime(when)
    m["From"] = frm
    m["To"] = to
    m["Subject"] = subject
    m["Message-ID"] = f"<{mid}>"
    if reply_to:
        m["In-Reply-To"] = f"<{reply_to}>"
        m["References"] = " ".join(f"<{r}>" for r in refs)
    m.set_content(body)
    if attach:
        name, data = attach
        m.add_attachment(data, maintype="application", subtype="pdf", filename=name)
    return m


uid = [9000]


def write(folder, m):
    uid[0] += 1
    ts = int(email.utils.parsedate_to_datetime(m["Date"]).timestamp())
    name = f"{ts}.M{uid[0]}P4242.devcorpus,U={uid[0]}:2,S"
    path = os.path.join(root, folder, "cur", name)
    with open(path, "wb") as f:
        f.write(m.as_bytes())
    os.utime(path, (ts, ts))
    print(folder, name, m["Subject"])


estimate = text_pdf([
    (16, "Bayside Tile & Bath"),
    (10, "118 Harbor Road, Port Example  -  estimates@baysidebath.example"),
    (10, ""),
    (13, "ESTIMATE #2231"),
    (10, "Date: August 18, 2026        Valid for 30 days"),
    (10, "Prepared for: Sam Rivera, 42 Cedar Lane"),
    (10, "Project: Master bathroom remodel"),
    (10, ""),
    (11, "Demolition and haul-away ............................ $1,200.00"),
    (11, "Tile (floor + shower surround), vanity, fixtures ...... $4,300.00"),
    (11, "Labor, approx. 6 working days ........................ $2,900.00"),
    (10, ""),
    (12, "TOTAL ................................................ $8,400.00"),
    (10, ""),
    (10, "Payment: 30% deposit ($2,520) to book, balance on completion."),
    (10, "Excludes: electrical work beyond replacing existing fixtures."),
    (10, "Permit fees, if required, billed at cost."),
])

BAY_EST = "estimate-2231@baysidebath.example"
write("INBOX", msg(
    BAY_EST, "Marco Bell <marco@baysidebath.example>", SAM,
    "Estimate #2231 - master bathroom remodel",
    datetime(2026, 8, 18, 16, 42, tzinfo=EDT),
    "Hi Sam,\n\nThanks for walking me through the space on Friday. The estimate for the "
    "master bathroom is attached - it covers demo, the tile and vanity we talked about, "
    "and labor. Everything is itemised on the PDF.\n\nThe price holds for 30 days. If you "
    "want to go ahead, a 30% deposit books you into our schedule.\n\nBest,\nMarco Bell\n"
    "Bayside Tile & Bath\n",
    attach=("Bayside-Estimate-2231.pdf", estimate)))

write("INBOX", msg(
    "quote-7781@keelplumb.example", "Keel & Plumb Renovations <office@keelplumb.example>", SAM,
    "Your bathroom renovation quote",
    datetime(2026, 8, 21, 10, 5, tzinfo=EDT),
    "Hello Sam,\n\nFollowing our site visit, here is our quote for the master bathroom "
    "renovation:\n\n  Full gut and disposal: $1,650\n  Heated tile floor + shower tile: $5,900\n"
    "  Vanity and fixtures (client-selected allowance): $1,400\n  Labor (8-9 days): $2,300\n\n"
    "  Total: $11,250\n\nWe could start in mid-November. Quote valid through September 30.\n\n"
    "Regards,\nJo Keel\nKeel & Plumb Renovations\n"))

ADA_NOTE = "bathroom-quotes-ada@example.com"
write("INBOX", msg(
    ADA_NOTE, ADA, SAM, "Bathroom quotes",
    datetime(2026, 8, 22, 20, 18, tzinfo=EDT),
    "I read both quotes. Keel & Plumb is nicer on paper (heated floor!) but it's almost "
    "$3k more and they can't start until November. Bayside's tile samples looked good and "
    "Marco was straightforward. I'd go with Bayside if they can start in early October - "
    "can you ask?\n\nA\n"))

SAM_Q = "sam-bayside-start@example.org"
write("Sent", msg(
    SAM_Q, SAM, "Marco Bell <marco@baysidebath.example>",
    "Re: Estimate #2231 - master bathroom remodel",
    datetime(2026, 8, 24, 9, 30, tzinfo=EDT),
    "Hi Marco,\n\nWe'd like to go ahead with estimate #2231. Is there any chance of an "
    "early-October start?\n\nThanks,\nSam\n",
    reply_to=BAY_EST, refs=(BAY_EST,)))

write("INBOX", msg(
    "bayside-schedule@baysidebath.example", "Marco Bell <marco@baysidebath.example>", SAM,
    "Re: Estimate #2231 - master bathroom remodel",
    datetime(2026, 8, 25, 14, 2, tzinfo=EDT),
    "Hi Sam,\n\nGreat news. We can hold Monday, October 5 as the start date if the "
    "$2,520 deposit comes in by September 15. We'll need the bathroom cleared the "
    "weekend before.\n\nMarco\n",
    reply_to=SAM_Q, refs=(BAY_EST, SAM_Q)))
