#!/usr/bin/env bash
# Install a client-agnostic stdio launcher for the Mailvec MCP server.
#
# Phase 5 wires multiple non-Claude local agents (Gemini CLI, Codex CLI,
# ChatGPT desktop) up to the same server. Each one spawns its MCP children
# differently — sanitized PATH, no DOTNET_ROOT, varying current-working-dir —
# so we centralize all the workarounds in a single launcher script that every
# client can point at by absolute path.
#
# After this runs, every supported client's config block reduces to:
#
#   command:  ~/.local/bin/mailvec-mcp-stdio
#   args:     [] (the launcher already passes --stdio)
#   env:      (none required — user config comes from
#             ~/Library/Application Support/Mailvec/appsettings.Local.json,
#             written by ops/install.sh and read by every Mailvec binary)
#
# This script:
#   1. Publishes Mailvec.Mcp framework-dependent to ~/.local/share/mailvec/mcp/
#      (TCC-friendly: outside ~/Documents, where Claude Desktop's children
#      can't open files).
#   2. Writes ~/.local/bin/mailvec-mcp-stdio with the env workarounds baked in.
#   3. Prints a smoke-test recipe so you can verify the launcher works
#      standalone before pasting its path into a client config.
#
# Idempotent — re-run whenever Mailvec.Core or Mailvec.Mcp changes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBLISH_DIR="$HOME/.local/share/mailvec/mcp"
LAUNCHER_PATH="$HOME/.local/bin/mailvec-mcp-stdio"

cd "$REPO_ROOT"

echo "→ Publishing Mailvec.Mcp to $PUBLISH_DIR ..."
dotnet publish src/Mailvec.Mcp/Mailvec.Mcp.csproj -c Release -o "$PUBLISH_DIR" --nologo --verbosity quiet
# Stable Developer ID signature so TCC grants persist across republish; ad-hoc
# fallback when no cert. See ops/sign-publish.sh.
source "$REPO_ROOT/ops/sign-publish.sh"
mailvec_sign_publish "$PUBLISH_DIR" "Mailvec.Mcp" "com.mailvec.mcp"
echo "✓ Published"

mkdir -p "$(dirname "$LAUNCHER_PATH")"

# Heredoc, not template substitution — keeps the launcher source-readable in
# `cat ~/.local/bin/mailvec-mcp-stdio` for live debugging on a target machine.
# All paths are resolved at runtime via $HOME so the script is portable across
# users (the install path is per-user, but if someone copies the launcher
# verbatim to another machine it still does the right thing).
cat > "$LAUNCHER_PATH" <<'LAUNCHER'
#!/usr/bin/env bash
# Mailvec MCP stdio launcher. Generated by ops/install-stdio-launcher.sh.
#
# Why this exists: MCP clients spawn server children with hostile environments —
# Claude Desktop sanitizes PATH (no /usr/local/share/dotnet), Gemini CLI inherits
# the user shell but not the user's interactive aliases, Codex CLI may run as a
# different uid in some sandboxing configurations, etc. Putting the workarounds
# in one place means client config blocks stay simple and identical.
#
# Behavior:
#   • Stdout is the JSON-RPC channel — never write to it from this script.
#   • All diagnostic output goes to stderr; the client may capture it to its
#     own log (Claude Desktop: ~/Library/Logs/Claude/mcp-server-mailvec.log).
#   • User config (DB / Maildir / Ollama / Fastmail) is read from the
#     shared ~/Library/Application Support/Mailvec/appsettings.Local.json
#     written by ops/install.sh — same file the launchd-installed services
#     and the CLI use. An agent that hard-codes its own env vars still wins
#     (env > shared file in the precedence chain).
#
# Smoke test (paste into a terminal):
#   ~/.local/bin/mailvec-mcp-stdio </dev/null
# expected: a few stderr log lines, then the process waits for JSON-RPC on
# stdin. ^C to exit. If you see a stack trace, the published binary is broken
# or DOTNET_ROOT can't find a runtime — fix that before pointing a client at
# this script.

set -euo pipefail

# Sanitized-PATH workaround. The official .NET macOS installer drops dotnet
# at /usr/local/share/dotnet, which Claude Desktop's spawned PATH excludes.
# Prepend the standard install locations so `dotnet` resolves regardless of
# how the parent was invoked.
export DOTNET_ROOT="${DOTNET_ROOT:-/usr/local/share/dotnet}"
export PATH="$DOTNET_ROOT:/usr/local/bin:/opt/homebrew/bin:$PATH"

# User config (DB path, Maildir, Ollama URL, Fastmail account id) is read
# from ~/Library/Application Support/Mailvec/appsettings.Local.json by the
# binary itself — no env-var defaults here. ops/install.sh writes that file
# (run it once and the values apply to every Mailvec binary, including this
# launcher's target). Clients that want to override anything can still set
# env vars in their MCP config; env vars win over the shared file.

PUBLISH_DIR="$HOME/.local/share/mailvec/mcp"
DLL="$PUBLISH_DIR/Mailvec.Mcp.dll"

if [[ ! -f "$DLL" ]]; then
    echo "ERROR: Mailvec.Mcp.dll not found at $DLL." >&2
    echo "       Run ops/install-stdio-launcher.sh from the Mailvec checkout to publish it." >&2
    exit 1
fi

# exec replaces this shell with the dotnet process so the client sees the
# binary's PID directly — cleaner shutdown signaling, no orphaned bash.
exec dotnet "$DLL" --stdio
LAUNCHER

chmod +x "$LAUNCHER_PATH"
echo "✓ Wrote launcher: $LAUNCHER_PATH"

cat <<DONE

Done. Smoke-test the launcher before wiring up a client:

    $LAUNCHER_PATH </dev/null

You should see a few stderr log lines, then the process waits for JSON-RPC on
stdin. ^C to exit.

To point a client at it, see docs/clients/ (per-client config snippets).
DONE
