#!/usr/bin/env bash
# Install a client-agnostic stdio launcher for the Mailvec MCP server.
#
# Phase 5 wires multiple non-Claude local agents (Gemini CLI, Codex CLI,
# ChatGPT desktop) up to the same server. Each one spawns its MCP children
# differently — sanitized PATH, no DOTNET_ROOT, varying current-working-dir —
# so we centralize all the workarounds in a single launcher script that every
# client can point at by absolute path.
#
# After this runs, every supported client's config block reduces to:
#
#   command:  ~/.local/bin/mailvec-mcp-stdio
#   args:     [] (the launcher already passes --stdio)
#   env:      Archive__DatabasePath=..., Ingest__MaildirRoot=..., Ollama__BaseUrl=...
#
# This script:
#   1. Publishes Mailvec.Mcp framework-dependent to ~/.local/share/mailvec/mcp/
#      (TCC-friendly: outside ~/Documents, where Claude Desktop's children
#      can't open files).
#   2. Writes ~/.local/bin/mailvec-mcp-stdio with the env workarounds baked in.
#   3. Prints a smoke-test recipe so you can verify the launcher works
#      standalone before pasting its path into a client config.
#
# Idempotent — re-run whenever Mailvec.Core or Mailvec.Mcp changes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBLISH_DIR="$HOME/.local/share/mailvec/mcp"
LAUNCHER_PATH="$HOME/.local/bin/mailvec-mcp-stdio"

cd "$REPO_ROOT"

echo "→ Publishing Mailvec.Mcp to $PUBLISH_DIR ..."
dotnet publish src/Mailvec.Mcp/Mailvec.Mcp.csproj -c Release -o "$PUBLISH_DIR" --nologo --verbosity quiet
echo "✓ Published"

mkdir -p "$(dirname "$LAUNCHER_PATH")"

# Heredoc, not template substitution — keeps the launcher source-readable in
# `cat ~/.local/bin/mailvec-mcp-stdio` for live debugging on a target machine.
# All paths are resolved at runtime via $HOME so the script is portable across
# users (the install path is per-user, but if someone copies the launcher
# verbatim to another machine it still does the right thing).
cat > "$LAUNCHER_PATH" <<'LAUNCHER'
#!/usr/bin/env bash
# Mailvec MCP stdio launcher. Generated by ops/install-stdio-launcher.sh.
#
# Why this exists: MCP clients spawn server children with hostile environments —
# Claude Desktop sanitizes PATH (no /usr/local/share/dotnet), Gemini CLI inherits
# the user shell but not the user's interactive aliases, Codex CLI may run as a
# different uid in some sandboxing configurations, etc. Putting the workarounds
# in one place means client config blocks stay simple and identical.
#
# Behavior:
#   • Stdout is the JSON-RPC channel — never write to it from this script.
#   • All diagnostic output goes to stderr; the client may capture it to its
#     own log (Claude Desktop: ~/Library/Logs/Claude/mcp-server-mailvec.log).
#   • Env vars passed by the spawning client win; this script only sets
#     defaults for vars the client didn't supply. So an agent that hard-codes
#     Archive__DatabasePath in its config gets that path; one that doesn't
#     falls back to the default we bake in here.
#
# Smoke test (paste into a terminal):
#   ~/.local/bin/mailvec-mcp-stdio </dev/null
# expected: a few stderr log lines, then the process waits for JSON-RPC on
# stdin. ^C to exit. If you see a stack trace, the published binary is broken
# or DOTNET_ROOT can't find a runtime — fix that before pointing a client at
# this script.

set -euo pipefail

# Sanitized-PATH workaround. The official .NET macOS installer drops dotnet
# at /usr/local/share/dotnet, which Claude Desktop's spawned PATH excludes.
# Prepend the standard install locations so `dotnet` resolves regardless of
# how the parent was invoked.
export DOTNET_ROOT="${DOTNET_ROOT:-/usr/local/share/dotnet}"
export PATH="$DOTNET_ROOT:/usr/local/bin:/opt/homebrew/bin:$PATH"

# Sensible config defaults for clients that don't override. The server reads
# Archive__DatabasePath / Ingest__MaildirRoot / Ollama__BaseUrl from env first
# (via Microsoft.Extensions.Configuration), falling back to appsettings.json
# next to the binary. Setting these here means a barebones client config
# (just the launcher path) still works against the standard install layout.
: "${Archive__DatabasePath:=$HOME/Library/Application Support/Mailvec/archive.sqlite}"
: "${Ingest__MaildirRoot:=$HOME/Mail/Fastmail}"
: "${Ollama__BaseUrl:=http://localhost:11434}"
export Archive__DatabasePath Ingest__MaildirRoot Ollama__BaseUrl

PUBLISH_DIR="$HOME/.local/share/mailvec/mcp"
DLL="$PUBLISH_DIR/Mailvec.Mcp.dll"

if [[ ! -f "$DLL" ]]; then
    echo "ERROR: Mailvec.Mcp.dll not found at $DLL." >&2
    echo "       Run ops/install-stdio-launcher.sh from the Mailvec checkout to publish it." >&2
    exit 1
fi

# exec replaces this shell with the dotnet process so the client sees the
# binary's PID directly — cleaner shutdown signaling, no orphaned bash.
exec dotnet "$DLL" --stdio
LAUNCHER

chmod +x "$LAUNCHER_PATH"
echo "✓ Wrote launcher: $LAUNCHER_PATH"

cat <<DONE

Done. Smoke-test the launcher before wiring up a client:

    $LAUNCHER_PATH </dev/null

You should see a few stderr log lines, then the process waits for JSON-RPC on
stdin. ^C to exit.

To point a client at it, see docs/clients/ (per-client config snippets).
DONE
